### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by paulirish** [jankuca/dom-panda#1]
this shit needs a demo! wanna see it in action! :)

**Comment by jankuca** [comment]
If Paul Irish says so...

Here are two demos. Wait for the rendering to show up in the upper right corner. You can also check the console to see how long does it take to render the page.

[Kittens](http://dom-panda.node.jankuca.com/example/kittens.html)
[Last.fm Page](http://dom-panda.node.jankuca.com/example/lastfm.html)

**Comment by paulirish** [comment]
thanks!!! :) 

hot shit
