### ISSUE TITLE
Dom-Panda vs HTML2Canvas Architecture

### ISSUE THREAD

**Issue by toymachiner62** [jankuca/dom-panda#5]
I'm evaluating tools to take a screenshot of the browser and I see that both Dom-Panda and HTML2Canvas seem to be what i'm evaluating. 

Does Dom-Panda and HTML2Canvas both function the same way architecturally in that they both read the DOM and basically use the canvas to create an image which can then be sent back to the server? Or is there some high level architectural differences between these 2?

**Comment by jankuca** [comment]
It should be very similar. DOM is traversed and style info is read for each node.
